#!/bin/sh

cd "$(dirname "$0")/.."

test -z "$NODE_ENV" &&
  export NODE_ENV='development'

echo "What is the Harmony Hub IP address?"

read hubIP

echo "What is the Harmony Hub name?"

read hubName

export HUB_IP=$hubIP
export HUB_NAME=$hubName

if [ "$NODE_ENV" = "development" ]; then
  /usr/bin/env forever -f config/forever/development.json
else
  /usr/bin/env forever start config/forever/production.json
fi
