#!/bin/sh

cd "$(dirname "$0")/.."

test -z "$NODE_ENV" &&
  export NODE_ENV='production'

echo $NODE_ENV

echo "What is the Harmony Hub IP address?"

read HUBIP

echo "What is the Harmony Hub name?"

read HUBNAME

export HUB_IP=$HUBIP
export HUB_NAME=$HUBNAME

if [ "$NODE_ENV" = "development" ]; then
  /usr/bin/env forever -f config/forever/development.json
else
  /usr/bin/env forever start config/forever/production.json
fi
